# Generated by Django 4.1.4 on 2022-12-17 22:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Tork-kee', max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='Images')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_disponible', models.DateField(default=datetime.date(2022, 12, 17))),
                ('date_reservation', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 22, 19, 31, 805016))),
                ('prix', models.DecimalField(decimal_places=3, max_digits=6)),
                ('dure_sejour', models.IntegerField()),
                ('nombre_personne', models.IntegerField()),
                ('date_ariver', models.DateField(verbose_name=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 22, 19, 31, 805016)))),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
    ]
