# Generated by Django 4.1.4 on 2022-12-17 23:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='date_reservation',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='dure_sejour',
        ),
        migrations.AlterField(
            model_name='chambre',
            name='date_ariver',
            field=models.DateField(default=datetime.date(2022, 12, 17)),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(default=datetime.datetime(2022, 12, 17, 23, 37, 19, 672260))),
                ('dure_sejour', models.IntegerField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.chambre')),
            ],
        ),
    ]
