# Generated by Django 4.1.4 on 2022-12-18 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_chambre_date_ariver_alter_chambre_date_depart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='chambre',
            new_name='hotel',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 11, 4, 32, 466033)),
        ),
    ]
