# Generated by Django 4.1.4 on 2022-12-18 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_chambre_chambre_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='date_disponible',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 11, 11, 6, 681113)),
        ),
    ]
