# Generated by Django 4.1.4 on 2022-12-18 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_chambre_disponible_alter_chambre_date_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='date_ariver',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='date_disponible',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 11, 12, 45, 760629)),
        ),
    ]
