# Generated by Django 4.1.4 on 2022-12-18 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_chambre_date_ariver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='date_depart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 11, 13, 28, 993208)),
        ),
    ]
