# Generated by Django 4.1.4 on 2022-12-18 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_chambre_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 11, 16, 42, 201633)),
        ),
    ]
