# Generated by Django 4.1.4 on 2022-12-18 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_chambre_occupe_alter_reservation_date_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='hotel',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 11, 37, 14, 504818)),
        ),
    ]
