# Generated by Django 4.1.4 on 2022-12-23 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_avis_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avis',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 10, 58, 58, 345010)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 10, 58, 58, 345896)),
        ),
    ]
