# Generated by Django 4.1.4 on 2022-12-23 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_reservation_prix_total_alter_avis_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 10, 59, 26, 628534)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 10, 59, 26, 629486)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
