# Generated by Django 4.1.4 on 2023-01-04 14:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0015_alter_avis_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 14, 40, 34, 558031)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 14, 40, 34, 559450)),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('date_envoi', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
