# Generated by Django 4.1.4 on 2022-12-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_user_profile_photo_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
