# Generated by Django 4.1.4 on 2022-12-12 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_sortie',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
    ]
