# Generated by Django 4.1.4 on 2022-12-10 12:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Directeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('date_sortie', models.DateField(default=datetime.date(2022, 12, 10))),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.categorie')),
                ('film_nationalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.pays')),
                ('pays_disponible', models.ManyToManyField(related_name='pays_disponible_film', to='films.pays')),
                ('realisateurs', models.ManyToManyField(to='films.directeur')),
            ],
        ),
    ]
