# Generated by Django 2.2.16 on 2022-12-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamberNum', models.IntegerField(default=0)),
                ('chamberPicture', models.ImageField(blank=True, null=True, upload_to='BookingRoom/templates/chamberPictures')),
                ('chamberDesc', models.TextField(null=True)),
                ('chamberUpdated', models.DateTimeField(auto_now=True)),
                ('chamberCreated', models.DateTimeField(auto_now_add=True)),
                ('chamberTicketPrice', models.IntegerField(default=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=200)),
                ('sectionUpdated', models.DateTimeField(auto_now=True)),
                ('SectionCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=200)),
                ('roomCreated', models.DateTimeField(auto_now_add=True)),
                ('roomUpdated', models.DateTimeField(auto_now=True)),
                ('roomDesc', models.TextField(null=True)),
                ('roomPlaceAvailabe', models.IntegerField(default=0)),
                ('roomPicture', models.ImageField(blank=True, null=True, upload_to='BookingRoom/templates/roomPictures')),
                ('roomOpenHour', models.TimeField(default='19:30:00')),
                ('roomCloseHour', models.TimeField(default='02:00:00')),
                ('roomPlace', models.CharField(default='Ouagadougou', max_length=200)),
                ('roomGeoLoc', models.CharField(default='Pissy', max_length=200)),
                ('roomOpenDay', models.CharField(default='Lundi-Dimanche', max_length=200)),
                ('roomHost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sectionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Section')),
            ],
            options={
                'ordering': ['-roomUpdated', '-roomCreated'],
            },
        ),
        migrations.CreateModel(
            name='Restauplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restauUpdated', models.DateTimeField(auto_now=True)),
                ('restauCreated', models.DateTimeField(auto_now_add=True)),
                ('restauTotalplace', models.IntegerField(default=60)),
                ('restauAvailableplaces', models.IntegerField(default=60)),
                ('restauTicketPrice', models.IntegerField(default=1500)),
                ('roomName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Room')),
            ],
        ),
        migrations.CreateModel(
            name='ResevationPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lieu', models.CharField(max_length=200)),
                ('Secteur', models.CharField(max_length=200)),
                ('Plat', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Heure', models.TimeField()),
                ('Prix', models.IntegerField()),
                ('Nom', models.CharField(max_length=200)),
                ('Prenom', models.CharField(max_length=200)),
                ('roomName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Room')),
            ],
        ),
        migrations.CreateModel(
            name='ResevationMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lieu', models.CharField(max_length=200)),
                ('Secteur', models.CharField(max_length=200)),
                ('MovieName', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Heure', models.TimeField()),
                ('Prix', models.IntegerField()),
                ('Nom', models.CharField(max_length=200)),
                ('Prenom', models.CharField(max_length=200)),
                ('Place', models.IntegerField()),
                ('roomName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Room')),
            ],
        ),
        migrations.CreateModel(
            name='ResevationChamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamberNum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Chamber')),
                ('roomName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateName', models.CharField(max_length=200)),
                ('plateDesc', models.TextField(null=True)),
                ('plateIngredient', models.TextField(default='secret')),
                ('platePicture', models.ImageField(blank=True, null=True, upload_to='BookingRoom/templates/platePictures')),
                ('plateCooker', models.CharField(default='Unknow', max_length=200)),
                ('plateType', models.CharField(default='Plat', max_length=200)),
                ('plateTicketPrice', models.IntegerField(default=1500)),
                ('PlateCreated', models.DateTimeField(auto_now_add=True)),
                ('PlateUpdated', models.DateTimeField(auto_now=True)),
                ('PlateMinCookTime', models.IntegerField(default=60)),
                ('PlateStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Statut')),
                ('roomName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Room')),
            ],
            options={
                'ordering': ['-PlateUpdated', '-PlateCreated'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=200)),
                ('movieDesc', models.TextField(null=True)),
                ('movieDuration', models.IntegerField(default=154)),
                ('movieLanguage', models.CharField(default='Unknow', max_length=200)),
                ('movieCreator', models.CharField(default='Unknow', max_length=200)),
                ('moviePicture', models.ImageField(blank=True, null=True, upload_to='BookingRoom/templates/moviePictures')),
                ('movieDiffDate', models.DateField(default='2023-01-01')),
                ('movieDiffHour', models.TimeField(default='00:00:00')),
                ('movieType', models.CharField(default='Cinema-Aventure-SF', max_length=200)),
                ('movieUpdated', models.DateTimeField(auto_now=True)),
                ('movieCreated', models.DateTimeField(auto_now_add=True)),
                ('movieAvailableplaces', models.IntegerField(default=24)),
                ('movieTicketPrice', models.IntegerField(default=1500)),
                ('movieStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Statut')),
                ('roomName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Room')),
            ],
            options={
                'ordering': ['-movieUpdated', '-movieCreated'],
            },
        ),
        migrations.AddField(
            model_name='chamber',
            name='ChamberStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Statut'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='chamberType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Type'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='roomName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Room'),
        ),
    ]
