# Generated by Django 2.2.16 on 2022-12-23 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resevationmovie',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2022, 12, 23)),
            preserve_default=False,
        ),
    ]
