# Generated by Django 2.2.16 on 2022-12-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRoom', '0003_auto_20221223_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResevationPlate',
        ),
    ]
