# Generated by Django 2.2.16 on 2022-12-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRoom', '0004_delete_resevationplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResevationPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lieu', models.CharField(max_length=200)),
                ('Secteur', models.CharField(max_length=200)),
                ('Plat', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Prix', models.IntegerField()),
                ('Nom', models.CharField(max_length=200)),
                ('Prenom', models.CharField(max_length=200)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('roomName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingRoom.Room')),
            ],
        ),
    ]
