# Generated by Django 2.2.16 on 2022-12-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRoom', '0005_resevationplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resevationplate',
            old_name='Plat',
            new_name='PlateName',
        ),
    ]
