# Generated by Django 2.2.16 on 2022-12-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRoom', '0006_auto_20221223_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resevationplate',
            old_name='PlateName',
            new_name='Plat',
        ),
    ]
