# Generated by Django 2.2.16 on 2022-12-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRoom', '0007_auto_20221223_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResevationPlate',
        ),
    ]
