# Generated by Django 4.1.3 on 2022-12-04 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_location',
            field=models.DateField(default=datetime.date(2022, 12, 4)),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_retour',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 12, 4)),
        ),
    ]
